### ISSUE TITLE
Line numbering broken on some devices

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-docs#167]
Mac OS (broken):

![image](https://user-images.githubusercontent.com/51940/104000430-20abb400-5196-11eb-8dbc-e1b63dd0badc.png)

Windows (working):

![image](https://user-images.githubusercontent.com/51940/104000455-2b664900-5196-11eb-8de8-f4866578d146.png)

**Comment by ghost** [comment]
@pierre - Is this still the case when you view on a Mac?

**Comment by pierre** [comment]
It looks better, except maybe for the contrast. Maybe a lighter color would be better?
<img width="872" alt="image" src="https://user-images.githubusercontent.com/51940/167076843-b2cc1705-6042-4175-9c06-c22ec8a2e5a2.png">

**Comment by pierre** [comment]
All good now!

<img width="1432" alt="image" src="https://github.com/killbill/killbill-docs/assets/51940/52da3b20-e6f3-4367-b8ad-0cbbd28749b7">
