### ISSUE TITLE
Invoice and payment relationships guide

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-docs#17]
Go over:
- Pure payment APIs use-cases
- Pure invoice APIs use-cases (external charges, credits, ...)
- Relationship between
  - Invoices and Payment
  - Subscription and Invoices

**Comment by sbrossie** [comment]
fyi: I had already added some [explanation on our a api doc](https://killbill.github.io/slate/#invoice-payment), but we should discuss what exactly.

**Comment by sbrossie** [comment]
@pierre Updated doc [here](https://github.com/killbill/killbill-docs/commit/29b44a9849cee23500df7289566358558189623b)
