### ISSUE TITLE
Libraries updates

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-docs#181]
Follow-ups on https://github.com/killbill/killbill-docs/pull/173:

- [x] Remove extra files docs/_config.yml and docs/index.md
- [x] Remove any extra CSS/JSS import (e.g. https://getbootstrap.com/docs/4.5/assets/css/docs.min.css or Algolia)
- [x] Fix logo / menu overlap on index.html page
![image](https://user-images.githubusercontent.com/51940/105673376-df2d3f80-5edd-11eb-80ec-7fdcc6bfa43e.png)
- [x] Update template files (e.g. https://github.com/killbill/killbill-docs/blob/v3/html5/document.html.slim) to make sure style.css works with all *generated* pages
- [x] Verify bootstrap-toc (https://afeld.github.io/bootstrap-toc/) works with Bootstrap 5 (i.e. that the menus are auto-generated properly in all pages)
- [x] Extra vertical line on the right on the TOC scrollbar ![image](https://user-images.githubusercontent.com/51940/106004671-5a901c00-60ab-11eb-928f-4f4d04d2fc87.png)
- [x] Extra horizontal line on the bottom of the TOC 
![image](https://user-images.githubusercontent.com/51940/106004761-7267a000-60ab-11eb-8197-b5f93a96118c.png)
- [x] The menu is automatically open on mobile 
![image](https://user-images.githubusercontent.com/51940/106004886-92975f00-60ab-11eb-9790-5b6d94d94436.png)
- [x] Extra left margin on the sub-entries
![image](https://user-images.githubusercontent.com/51940/106005000-afcc2d80-60ab-11eb-88c1-eac88efaa49d.png)
- [x] Code is white on white (see also https://nekores.github.io/killbill-docs/build/selfcontained/getting_started.html) 
![image](https://user-images.githubusercontent.com/51940/106005383-16514b80-60ac-11eb-96ea-388aa1cb133d.png)
- [x] Could we lower the height of the footer? 
![image](https://user-images.githubusercontent.com/51940/106006174-d5a60200-60ac-11eb-989d-a191569fd7f4.png)

**Acceptance criteria**: for the task to be complete, all pages (e.g. https://docs.killbill.io/latest/getting_started.html) must have a similar CSS and existing functionality should not be broken (e.g. menus or code highlighting).

**Comment by Nekores-zz** [comment]
Hi @pierre ,
I fixed all the changes in sequence. Let me know, If you need anything else. thank you!
