### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-docs#184]
Integrate with https://docsearch.algolia.com/.

**Comment by pierre** [comment]
I've submitted the site -- waiting for approval and API key.

**Comment by pierre** [comment]
- Copy the following CSS/JS snippets and add them to your page
```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: '9d2f6d24a05863f83c8844f6e7492c66',
indexName: 'killbill',
inputSelector: '### REPLACE ME ####',
debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet
to a CSS selector that targets your search input field.
- Optionally customize the look and feel by following the DocSearch documentation
(See https://docsearch.algolia.com/docs/styling/)

**Comment by Nekores-zz** [comment]
@pierre , All right, I am working on this, I will be able to create the final PR by tomorrow.
