### ISSUE TITLE
Overdue system docs problem.

### ISSUE THREAD

**Issue by yubinnng** [killbill/killbill-docs#234]
the [overdue docs](https://docs.killbill.io/latest/overdue.html) indicates that plugin-installation API is :

```bash
curl -v \
-u admin:password \
-H "Content-Type: application/json" \
-H 'X-Killbill-CreatedBy: stephane' \
-X POST \
--data-binary '{"systemCommandType":"true","nodeCommandType":"INSTALL_PLUGIN","nodeCommandProperties":[{"key":"pluginKey", "value":"payment-test"},{"key":"pluginArtifactId", "value": "payment-test-plugin"},{"key":"pluginGroupId", "value": "org.kill-bill.billing.plugin.ruby"}, {"key": "pluginType", "value": "ruby"} ]}' \
"http://127.0.0.1:8080/1.0/kb/nodesInfo"
```

However, the correct field name is `isSystemCommandType` rather `systemCommandType`.

And thank you for opensource such an awesome project.

**Comment by yubinnng** [comment]
Maybe a serialization problem?

**Comment by reshmabidikar** [comment]
I've already fixed this while updating the overdue document. I've moved the plugin installation command to the Plugin Development document [here](https://docs.killbill.io/latest/plugin_development.html#_deploying_via_plugin_management_apis).

**Comment by pierre** [comment]
Thank you!
