### ISSUE TITLE
AWS documentation is out of date

### ISSUE THREAD

**Issue by danieljue** [killbill/killbill-docs#30]
(placeholder for potential PR)
https://github.com/killbill/killbill-docs/blob/v3/userguide/tutorials/aws.adoc  

Shows out of date DDLs and Docker tags and blog links.

**Comment by sbrossie** [comment]
@danieljue Would you be willing to submit a PR to fix the issues you have seen?

**Comment by pierre** [comment]
See http://docs.killbill.io/0.20/aws.html.
