### ISSUE TITLE
Unclear definitions for "entitlement" and "subscription"

### ISSUE THREAD

**Issue by farialima** [killbill/killbill-docs#4]
There's no clear definition of these concepts in the doc, and they are non-trivial for a newbie.

in http://docs.kill-bill.org/userguide.html I find a definition for entitlement:
"An Entitlement encapsulates all the information that pertains to the entitlement question" which is recursive and not very clear; and "A Subscription is a meta abstraction that encapsulates the Entitlement and adds additonal billing information." which is not very clear either (I'm not sure what a "meta abstraction" is... also note the typo "additonal")

Here's some simplier definition that I would suggest:
"An entitlement determines whether a user is allowed to use a product a product at a given time. It refers a plan (i.e. product definition, billing period definition - monthly, yearly…) as well as possibly information about start/end date of access to the product. However, entitlements don't include billing information - they don't have anything about when and how much the user will be billed: they are only about usage of the product."

"A subscription defines how the entitlement given to the account will be billed: it includes entitlement information, and adds to it billing information such as billing start date, end date"

Probably having a clear glossary / concept definition section with these definition (as well as: Bundle; Plan; and probably a few others) would help _a lot_.

Thanks Kevin P. for help on this :)

**Comment by farialima** [comment]
Some more possible suggestions / elements:
"A subscription is associated with a user and a catalog entry at a particular time."
and "Billing and entitlement are tracked at the subscription level and payments are made associated with the subscription." which is the important point: Subscription defines how billing happens, whereas entitlement defines how the product is used.

**Comment by martinwesthead** [comment]
Hi farialima,

The best way to think of a Plan is that is specifies HOW a customer pays,
in contrast to a product that specifies WHAT a customer buys. If you look
at the section on the Catalog, sopecifically the subsections "Background
Concepts" and "What's in a catalog" you can find definitions for some of
these terms.

I think adding a glossary is a great idea, we should do that.

Thanks,

Martin

**Comment by farialima** [comment]
the http://docs.kill-bill.org/userguide.html#_background_concepts  is somewhat useful, but it mixes up general concepts (Bundle...) and completely application-usage level (the fact that there are _two_ types of admin). 

Also BTW - isn't a Bundle a pointer to a usage of the product ? (bundle_external_key = network at ning right ?) so wouldn't a better example (in the case of phone) say "a bundle represents a phone - referenced by its phone number" ? also I couldn't understand in the example if the "plan" - data plan, voice plan - would actually be "Plans" as defined in KB...

**Comment by farialima** [comment]
(my apologies for criticizing the docs - but really I would say that usage from the product will come if people understand the concepts - and you have to plan your users to be very dumb - as dumb as me :D - I'm just trying to understand, and give feedback while at it)

**Comment by sbrossie** [comment]
@farialima I agree with you. The definition of Entitlement is indeed pretty confusing (and recursive) which does not help. I will incorporate your suggestion in the doc. Thanks for pointing that out.
