### ISSUE TITLE
remove bundlesPath and kpmPath

### ISSUE THREAD

**Issue by xsalefter** [killbill/killbill-docs#487]
In [setting up KPM in KAUI](https://docs.killbill.io/latest/getting_started.html#_setting_up_kpm_in_kaui), we still have references to `bundlesPath` and `kpmPath`. 

```
org.killbill.billing.plugin.kpm.bundlesPath=<kpm_bundles_path>
org.killbill.billing.plugin.kpm.kpmPath=<kpm_path>
```

Those are removed by this issue (its tasks and sub-sequence PRs): https://github.com/killbill/technical-support/issues/58. But we can't do it now (at the time of writing). Should wait at least after on going (at the time of writing) release.

**Comment by reshmabidikar** [comment]
Addressed by @xsalefter  in https://github.com/killbill/killbill-docs/pull/491. Closing this issue.
