### ISSUE TITLE
New docs site issue: Black area displayed when video is being played

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-docs#505]
When a video is being played on the docs site, UI displays a black area above and below the video:

<img width="359" alt="black-space-around-video" src="https://github.com/killbill/killbill-docs/assets/85998496/77dc45a2-78ca-48b6-9142-87996246c5de">

Not sure if this has something to do with the browser/screen resolution.

**Comment by reshmabidikar** [comment]
https://github.com/killbill/killbill-docs/pull/515 addresses this. The video now plays in a new browser window that opens youtube.com. It displays youtube ads. The docs site displays the video preview screen. 

The following screen recording demonstrates this:

https://www.loom.com/share/d5b0c00d9bea4212b3b0679da8a3395f?sid=3b3a0859-a576-4acc-a603-255508a1ce2e

 @pierre Is this the desired behavior?

**Comment by pierre** [comment]
Good catch, without YT Premium, one has ads 😞 I've filed https://github.com/killbill/killbill-docs/issues/518 for tracking.

**Comment by deekant** [comment]
@reshmabidikar @pierre these are two different videos. This issue started for embedded video with black areas on the index page https://new-branding.docs-killbill-io.pages.dev/ and it's fixed there.

And the second one is on https://new-branding.docs-killbill-io.pages.dev/latest/what_is_kill_bill with a popup and redirect to Youtube. Maybe we make it embedded as well?

**Comment by pierre** [comment]
Yup, that sounds good!
