### ISSUE TITLE
New docs site: White space displayed around text

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-docs#507]
White space is displayed on either side of the page content:

<img width="751" alt="image" src="https://github.com/killbill/killbill-docs/assets/85998496/74c817fc-a45c-459f-85b8-0a50cf43b40d">

Is this intentional? It seems to make the page unnecessarily long and users require additional scrolling.

**Comment by reshmabidikar** [comment]
**Update:** This might be a browser thing. When I zoom out the browser, the white space is reduced:

<img width="741" alt="image" src="https://github.com/killbill/killbill-docs/assets/85998496/c2dc5f2a-30ea-42c5-9e33-c94ed7cbddcb">

**Comment by deekant** [comment]
@reshmabidikar what screen width/device is this on your screenshots?

**Comment by reshmabidikar** [comment]
I'm on Windows/Microsoft Edge browser. The following are my display settings:

<img width="713" alt="image" src="https://github.com/killbill/killbill-docs/assets/85998496/cf515737-ec59-4870-b0b1-5fb58d09d091">


The extra white space is shown when the zoom setting is `100%` in my browser:

<img width="892" alt="image" src="https://github.com/killbill/killbill-docs/assets/85998496/ecec39a0-2902-4f27-b212-c4d73d88d35b">


The white space is reduced when I change the zoom setting to `90%`:

<img width="738" alt="image" src="https://github.com/killbill/killbill-docs/assets/85998496/533afdc9-47f7-441d-aa51-4106f999ca73">

**Comment by reshmabidikar** [comment]
https://github.com/killbill/killbill-docs/pull/515 addresses this, white space is no longer displayed:

<img width="921" alt="image" src="https://github.com/killbill/killbill-docs/assets/85998496/0e5f83eb-551c-4760-b435-e8945fe540e0">

Closing this issue.
