### ISSUE TITLE
New website: Color of code snippet boxes in dark mode

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-docs#508]
Should we change the color of the code snippet boxes in Dark mode? It is a bit difficult to distinguish the code snippet box from the rest of the text:

<img width="626" alt="image" src="https://github.com/killbill/killbill-docs/assets/85998496/826ce010-ec2d-48d1-b99b-4e5e23be9f78">

**Comment by pierre** [comment]
Agreed. Even in light mode, we should review the colours. The contrast is 📸!

<img width="901" alt="image" src="https://github.com/killbill/killbill-docs/assets/51940/e170365a-e8e1-4a0b-b243-0be1c178fbbe">

**Comment by pierre** [comment]
The text contrast is hard on the eyes too: 
<img width="921" alt="image" src="https://github.com/killbill/killbill-docs/assets/51940/9b190be1-fe60-48c6-b2d5-f6fce1dcb639">

**Comment by reshmabidikar** [comment]
https://github.com/killbill/killbill-docs/pull/515 addresses this. The colors now look good to me. @pierre, @sbrossie could you please also take a look once?

**Comment by pierre** [comment]
Yup, much easier on the eyes!
