### ISSUE TITLE
Missing right hand navigation with new design

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-docs#511]
Compare https://docs.killbill.io/latest/how-to-set-up-a-single-tier-system.html with https://new-branding.docs-killbill-io.pages.dev/latest/how-to-set-up-a-single-tier-system: the right navbar is missing.

**Comment by deekant** [comment]
@pierre I can see the right nav bar on both pages. Or am I confusing something?

![Screenshot 2023-08-11 at 11 42 11](https://github.com/killbill/killbill-docs/assets/33588094/3fbf28c2-6a26-4f4f-8eea-6449291c1c65)

**Comment by pierre** [comment]
🤔 

@reshmabidikar Could you check if you see the navbar at https://new-branding.docs-killbill-io.pages.dev/latest/how-to-set-up-a-single-tier-system?

<img width="1427" alt="image" src="https://github.com/killbill/killbill-docs/assets/51940/1b689699-de85-4472-a1ed-5fdb706ae1ec">

**Comment by pierre** [comment]
Nevermind, this is expected at 1400px (13" laptop).

**Comment by pierre** [comment]
Fixed on the 13".
