### ISSUE TITLE
OSGI JDBC configuration property name seems wrong

### ISSUE THREAD

**Issue by pfumagalli** [killbill/killbill-docs#6]
Deploying my plugin, I've used the `org.killbill.billing.osgi.jdbc.url` system property name, but that seems to have changed somewhere in the code...

I noticed that by setting the `org.killbill.billing.osgi.dao.url` everything seems to work all-right!

**Comment by pierre** [comment]
Thanks! You are right, it changed last year. FYI, the source code is in [OSGIDataSourceConfig](https://github.com/killbill/killbill-platform/blob/master/osgi/src/main/java/org/killbill/billing/osgi/glue/OSGIDataSourceConfig.java).
