### ISSUE TITLE
KillBill Doc: payments.state_names can be improved

### ISSUE THREAD

**Issue by kevinpostlewaite** [killbill/killbill-docs#7]
http://docs.killbill.io/0.14/userguide_payment.html#_payment_states_and_abstractions

Change FAILED,ERRORED (x2) to {AUTH,CAPTURE,..}_FAILED,  {AUTH,CAPTURE,..}_ERRORED

Change {AUTH,CAPTURE,..}_PENDING -->{AUTH,PURCHASE}_PENDING

**Comment by pierre** [comment]
Did [this commit](https://github.com/killbill/killbill-docs/commit/3b396e4e381c031f20eb7d8d462b116ad65ce2e0) address your concerns?

**Comment by kevinpostlewaite** [comment]
It addressed the first and much more important issue. I don't see that it fixed the second issue but that one doesn't matter much so I think it's fine to close this issue.

**Comment by pierre** [comment]
>  I don't see that it fixed the second issue

We have more `PENDING` cases now (e.g. `CREDIT_PENDING`), it's not just for `AUTH` or `CAPTURE`.
